### ISSUE TITLE
Performance/Crash issue when load multiple rails and hold arrow keys to navigate

### ISSUE THREAD

**Issue by bff12** [NoriginMedia/react-spatial-navigation#107]
**Describe the bug**
When we load multiple rails in our application and hold the button (up or down arrow for example) to navigate between items on those rails navigation is very slow and imprecise. We tried to use throttle, but we lost some functionality related to item placement. Would there be any alternative to handle the event of holding a key to navigate between items?

 For our app, an ideal behavior would be to treat the pressed key as if it were a key being pressed once and repeat that key again only once.

 Sometimes the application crashes, especially on TVs with less hardware(<=2018 in our scenario).

**To Reproduce**
Hold a key to navigate between items

**Expected behavior**
A fluid navigation with less loss of performance.

**Comment by predikament** [comment]
This issue sounds like an issue with how the library is being used rather than an issue with the library itself.

Let us know if you still have this problem - You can just reopen the issue if it's still a relevant problem for you. 

When reopening we would ask you kindly to please add more examples of the issue at hand, alongside details of your implementation so we can better understand the problem you are facing. 

I would also recommend elaborating a bit on details like "We have multiple rails", since "rails" is not necessarily a globally understood name or concept. I assume you mean rows or columns of content, but we might not be even be on the same page there.
